# Generated by Django 5.0 on 2024-01-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_customuser_custom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='custom_name',
        ),
    ]
