# Generated by Django 5.0 on 2024-01-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_customuser_call_me'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
